import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";


export component UI inherits Window {
    width: 240px;
    height: 280px;

    AboutSlint {}
    
    Button {
        property <bool> is_clicked: false;
        y: 150px;
        text: self.is_clicked ? "cliked!" : "click me";
        clicked => {
            self.is_clicked = !self.is_clicked;
        }
    }
}